### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by ArjunaKumarMohanta** [Cosmic-Ide/rewrite#103]
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
	... 1 more
Caused by: java.util.zip.ZipException: File too short to be a zip file: 0
	at java.util.zip.ZipFile.<init>(ZipFile.java:217)
	at java.util.zip.ZipFile.<init>(ZipFile.java:303)
	at org.cosmicide.fragment.ProjectOutputFragment$ssvm$2.invoke(ProjectOutputFragment.kt:205)
	at org.cosmicide.fragment.ProjectOutputFragment$ssvm$2.invoke(ProjectOutputFragment.kt:203)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.cosmicide.fragment.ProjectOutputFragment.getSsvm(ProjectOutputFragment.kt:203)
	at org.cosmicide.fragment.ProjectOutputFragment.onDestroy(ProjectOutputFragment.kt:266)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3376)
	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:812)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:346)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.kt:664)
	at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.kt:587)
	at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.kt:774)
	at androidx.fragment.app.DefaultSpecialEffectsController$startAnimations$1.onAnimationEnd(DefaultSpecialEffectsController.kt:193)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1296)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1081)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:693)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6865)
	... 3 more
```

**Comment by PranavPurwar** [comment]
Try clearing cache from app settings and reinstalling the files

**Comment by PranavPurwar** [comment]
Removed SSVM altogether
