### ISSUE TITLE
[bug] crash when cloning private repository

### ISSUE THREAD

**Issue by andihasan97** [Cosmic-Ide/rewrite#55]
app crashes when cloning private repository, even though i have git configured in settings: user.name, user.email, credential token, i tested the last build on github action

https://github.com/Cosmic-Ide/rewrite/assets/96150715/7017c221-9550-4f87-9e78-b1434e329f3c

**Comment by andihasan97** [comment]
here is the crash log cloning the private repository 

Build version: 1.0-11d229a 
Build date: 1981-01-01 01:01:02 
Current date: 2023-07-23 11:47:44 
Device: Vivo 1901 
 
Stack trace:  
org.eclipse.jgit.api.errors.TransportException: https://github.com/andihasan97/hisab-inkasyaf.git: Authentication is required but no CredentialsProvider has been registered
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:249)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:325)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:191)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:1)
	at com.github.syari.kgit.KGitCommand.call(KGitCommand.kt:10)
	at com.github.syari.kgit.KCloneCommand.callAsK(KCloneCommand.kt:19)
	at dev.pranav.jgit.tasks.RepositoryKt.cloneRepository(Repository.kt:165)
	at org.cosmicide.rewrite.fragment.ProjectFragment$gitClone$1$1$1.invokeSuspend(ProjectFragment.kt:248)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6d8c4e0, Dispatchers.IO]
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/andihasan97/hisab-inkasyaf.git: Authentication is required but no CredentialsProvider has been registered
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:689)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:465)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:153)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:105)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1462)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:238)
	... 15 more

User actions: 
2023-07-23 11:46:44: MainActivity created
2023-07-23 11:46:45: MainActivity resumed

**Comment by andihasan97** [comment]
still crash :
Build version: 1.0-ff2e015 
Build date: 1981-01-01 01:01:02 
Current date: 2023-07-23 15:34:41 
Device: Vivo 1901 
 
Stack trace:  
org.eclipse.jgit.api.errors.JGitInternalException: Creating directories for /hisab-inkasyaf.git:/.git failed
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:106)
	at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:282)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:182)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:1)
	at com.github.syari.kgit.KGitCommand.call(KGitCommand.kt:10)
	at com.github.syari.kgit.KCloneCommand.callAsK(KCloneCommand.kt:19)
	at dev.pranav.jgit.tasks.RepositoryKt.cloneRepository(Repository.kt:174)
	at org.cosmicide.rewrite.fragment.ProjectFragment$gitClone$1$1$1.invokeSuspend(ProjectFragment.kt:250)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8e2bc8, Dispatchers.IO]
Caused by: java.io.IOException: Creating directories for /hisab-inkasyaf.git:/.git failed
	at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:413)
	at org.eclipse.jgit.internal.storage.file.FileRepository.create(FileRepository.java:231)
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:103)
	... 15 more

User actions: 
2023-07-23 15:33:27: MainActivity created
2023-07-23 15:33:28: MainActivity resumed

**Comment by PranavPurwar** [comment]
Try to remove `.git` suffix from the url that you entered

**Comment by andihasan97** [comment]
> Try to remove `.git` suffix from the url that you entered

it worked, but every time the clone finishes, the application forces close 

https://github.com/Cosmic-Ide/rewrite/assets/96150715/6892d954-4f77-487a-a871-fb15a8299baa

**Comment by TheRemakerMan** [comment]
> > Try to remove `.git` suffix from the url that you entered
> 
> it worked, but every time the clone finishes, the application forces close 
> 
> https://github.com/Cosmic-Ide/rewrite/assets/96150715/6892d954-4f77-487a-a871-fb15a8299baa
> 
> 

It's strange that it works fine for me.
https://github.com/Cosmic-Ide/rewrite/assets/95296093/ae39682e-f4ad-4f3e-88db-74e45501e2c6

**Comment by PranavPurwar** [comment]
Might be some issue with how JGit handles private repos internally
