### ISSUE TITLE
App Crash 

### ISSUE THREAD

**Issue by Siddhesh2377** [Cosmic-Ide/rewrite#76]
Build version: 1.0-f9c1297 
Build date: 1981-01-01 01:01:02 
Current date: 2023-08-01 01:05:10 
Device: Xiaomi M2101K7BI 
 
Stack trace:  
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.cosmicide.rewrite/org.cosmicide.rewrite.MainActivity}: java.lang.NumberFormatException: For input string: "default"
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3775)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4018)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2427)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8232)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.NumberFormatException: For input string: "default"
	at java.lang.Integer.parseInt(Integer.java:747)
	at java.lang.Integer.parseInt(Integer.java:865)
	at org.cosmicide.rewrite.MainActivity.<init>(MainActivity.kt:30)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1359)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3762)
	... 12 more

User actions:

**Comment by PranavPurwar** [comment]
The crash should be fixed now, please reinstall the app again from [here](https://nightly.link/Cosmic-Ide/rewrite/workflows/android/main/apk-debug.zip)
