### ISSUE TITLE
Crash Open Settings 

### ISSUE THREAD

**Issue by scto** [Cosmic-Ide/rewrite#91]
Build version: 1.0-9f41831 
Build date: 1981-01-01 01:01:02 
Current date: 2023-08-14 03:40:27 
Device: Google Pixel 6 Pro 
 
Stack trace:  
java.lang.IllegalStateException: binder haven't been received
	at rikka.shizuku.Shizuku.requireService(Shizuku.java:430)
	at rikka.shizuku.Shizuku.getVersion(Shizuku.java:526)
	at org.cosmicide.rewrite.util.CommonUtils.isShizukuGranted(CommonUtils.kt:85)
	at org.cosmicide.rewrite.fragment.settings.AboutSettings.provideSettings(AboutSettings.kt:110)
	at org.cosmicide.rewrite.fragment.SettingsFragment.onViewCreated(SettingsFragment.kt:94)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

User actions: 
2023-08-14 03:40:06: MainActivity created
2023-08-14 03:40:07: MainActivity resumed

**Comment by scto** [comment]
Thanks
