### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ThatMG393** [Cosmic-Ide/rewrite#97]
When clicking the <- button at top left in the `Running {projectName}` and `Compilating {projectName}` it crashes.

**Logs:**
```
Build version: 1.0-65534bf 
Build date: 1981-01-01 01:01:02 
Current date: 2023-08-20 12:52:42 
Device: Samsung SM-A136B 
 
Stack trace:  
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	... 1 more
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:265)
	at java.util.zip.ZipFile.<init>(ZipFile.java:322)
	at org.cosmicide.rewrite.fragment.ProjectOutputFragment$ssvm$2.invoke(ProjectOutputFragment.kt:205)
	at org.cosmicide.rewrite.fragment.ProjectOutputFragment$ssvm$2.invoke(ProjectOutputFragment.kt:203)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.cosmicide.rewrite.fragment.ProjectOutputFragment.getSsvm(ProjectOutputFragment.kt:203)
	at org.cosmicide.rewrite.fragment.ProjectOutputFragment.onDestroy(ProjectOutputFragment.kt:266)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3376)
	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:812)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:346)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1934)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	... 3 more

User actions: 
2023-08-20 12:48:35: MainActivity created
2023-08-20 12:48:36: MainActivity resumed
2023-08-20 12:48:53: MainActivity paused
2023-08-20 12:48:53: MainActivity created
2023-08-20 12:48:53: MainActivity resumed
2023-08-20 12:48:53: MainActivity destroyed
2023-08-20 12:50:26: MainActivity paused
2023-08-20 12:50:35: MainActivity resumed
2023-08-20 12:50:45: MainActivity paused
2023-08-20 12:50:52: MainActivity resumed
2023-08-20 12:50:54: MainActivity paused
2023-08-20 12:51:00: MainActivity resumed

```

**Comment by TheRemakerMan** [comment]
It looks like you haven't downloaded or not completely downloaded the resources.

**Comment by PranavPurwar** [comment]
@ThatMG393 Try going to settings -> About -> Clear cache and reinstall all the files

**Comment by ThatMG393** [comment]
fixed now thanks!
