### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ThatMG393** [Cosmic-Ide/rewrite#98]
All I did was open a file.

**Logs:**
```
Build version: 1.0-65534bf 
Build date: 1981-01-01 01:01:02 
Current date: 2023-08-20 18:39:38 
Device: Samsung SM-A136B 
 
Stack trace:  
java.lang.RuntimeException: Duplicate registration for EP 'com.intellij.virtualFileManagerListener': first in fakeIdForTests, second in fakeIdForTests
	at com.intellij.mock.MockComponentManager.createError(MockComponentManager.java:81)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.checkThatPointNotDuplicated(ExtensionsAreaImpl.java:207)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.doRegisterExtensionPoint(ExtensionsAreaImpl.java:173)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.registerExtensionPoint(ExtensionsAreaImpl.java:145)
	at com.intellij.openapi.extensions.ExtensionsArea.registerExtensionPoint(ExtensionsArea.java:23)
	at org.cosmicide.completion.java.parser.CompletionProvider$Companion.registerExtensions(CompletionProvider.kt:145)
	at org.cosmicide.completion.java.parser.CompletionProvider.<init>(CompletionProvider.kt:200)
	at org.cosmicide.rewrite.editor.language.TsLanguageJava$1.invokeSuspend(TsLanguageJava.kt:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f21b17b, Dispatchers.IO]

User actions: 
2023-08-20 18:39:05: MainActivity created
2023-08-20 18:39:06: MainActivity resumed
```

**Comment by PranavPurwar** [comment]
Are you sure that you are on the latest debug build? I have already updated the code to check for duplicate extensions, so I'm not sure how this is happening to you
